export class StatisticOperations {
  constructor() {}
  onlyNumberColumnFilter(
    dataType: Record<string, string>,
    columns: string[]
  ): string[] {
    if (
      !dataType ||
      !Object.keys(dataType).length ||
      !columns ||
      !columns.length
    ) {
      return [];
    }
    let eligibleColumns: string[] = [];
    columns.forEach((column) => {
      if (dataType[column] === "number") {
        eligibleColumns.push(column);
      }
    });
    return eligibleColumns;
  }

  // Return the count.
  count(data: any[]): number {
    if (!data || !data.length) return NaN;
    return data.length;
  }

  // Calculate the sum.
  // AI Generated Code
  sum(data: number[]): number {
    if (!data || !data.length) return NaN;
    return data.reduce((sum, value) => sum + value, 0);
  }

  // Calculate the min.
  // AI Generated Code
  min(data: number[]): number {
    if (!data || !data.length) return NaN;
    return data.reduce((min, value) => (min < value ? min : value), Infinity);
  }

  // Calculate the max.
  // AI Generated Code
  max(data: number[]): number {
    if (!data || !data.length) return NaN;
    return data.reduce((max, value) => (max > value ? max : value), -Infinity);
  }

  // Partially Generated By AI
  // Added corner case Handling
  mean(data: number[]): number {
    let sum = 0;
    if (!data || !data.length) return NaN;
    return data.reduce((sum, current) => sum + current) / data.length;
  }

  // Partially Generated By AI
  // Added the corner case handling for the case sum = 0.
  // The answer should not return sum/2.
  median(data: number[]): number {
    if (!data || !data.length) return NaN;
    const sortedData = data.sort((a, b) => a - b); // Sort in ascending order

    if (sortedData.length % 2 === 0) {
      const middle1 = sortedData[sortedData.length / 2 - 1];
      const middle2 = sortedData[sortedData.length / 2];
      return (middle1 + middle2) / 2;
    }

    return sortedData[Math.floor(sortedData.length / 2)];
  }

  // Calculate the mode.
  mode(data: any[]): Record<any, number> {
    const ans: Record<any, number> = {};
    if (!data || !data.length) {
      return ans;
    }
    data.forEach((value) => {
      if (!ans[value]) {
        ans[value] = 0;
      }
      ans[value] = ans[value] + 1;
    });
    return ans;
  }

  // Calculate the variance.
  variance(data: number[]): number {
    if (!data || data.length < 2) return NaN;

    const mean = this.mean(data);
    const squaredDifferencesSum = data.reduce((sum, value) => {
      const difference = value - mean;
      return sum + difference * difference;
    }, 0);

    return squaredDifferencesSum / (data.length - 1);
  }

  // Calculate the standard deviation.
  // AI Generated Code
  standardDeviation(data: number[]): number {
    if (!data || !data.length) return NaN;
    return Math.sqrt(this.variance(data));
  }
}
